// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqgkN56wzf49eRFV1Nc9omJXLwkIfCABw',
    appId: '1:824943356058:web:1e3e7345b3b8fad0459723',
    messagingSenderId: '824943356058',
    projectId: 'trips-c7e7b',
    authDomain: 'trips-c7e7b.firebaseapp.com',
    storageBucket: 'trips-c7e7b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2_43O9PQgljlI7iEjs3T7lrpt45nC0Cs',
    appId: '1:824943356058:android:125629ea287ae18d459723',
    messagingSenderId: '824943356058',
    projectId: 'trips-c7e7b',
    storageBucket: 'trips-c7e7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcTaQoltXFg7VXByp4aaHphVL4Xey-37Y',
    appId: '1:824943356058:ios:a72d78dc8e707a3a459723',
    messagingSenderId: '824943356058',
    projectId: 'trips-c7e7b',
    storageBucket: 'trips-c7e7b.appspot.com',
    iosClientId: '824943356058-1t2lmv6o477mkvvknjnrvtcderk9ikkk.apps.googleusercontent.com',
    iosBundleId: 'com.example.trips',
  );
}
